### PR TITLE
Rework

### PR DESCRIPTION
**Pull request by RyadaProductions**
Saw this shared on /r/globaloffensive and thought i wanted to help out by making it even better :)

major changes are:
+ .gitignore file
This makes sure that temp/local files are not commited with the solution since other people don't need them
* changed the timer into a background worker
A timer was fine, but since we wanted to update a label with the status i figured a backgroundworker would do the job even better
* changed method/variable/control names to follow the standard conventions
- removed all files that the .gitignore should have prevented from being uploaded
- removed the RECT class as it was basically a duplicate of the Rect class in the .NET framework.

### CODE REVIEW

**Comment by RyadaProductions** [comment]
If you have any questions feel free to ask. Also i figured it might be cool to join the /r/csharp discord where a lot of people are willing to help/explain things about C#.
Here is the link: https://discord.gg/FTqNnyS

**Comment by blaberry** [comment]
- Error	CS0103	The name 'procid' does not exist in the current context	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	71	Active
 - Error	CS0118	'Rect' is a type but is used like a variable	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	67	Active
 - Error	CS1525	Invalid expression term 'uint'	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	70	Active
 - Error	CS1003	Syntax error, ',' expected	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	67	Active
 - Error	CS1003	Syntax error, ',' expected	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	70	Active
 - Error	CS0103	The name 'appBounds' does not exist in the current context	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	67	Active
 - Error	CS0103	The name 'appBounds' does not exist in the current context	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	73	Active
 - Error	CS0103	The name 'appBounds' does not exist in the current context	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	73	Active
 - Error	CS0103	The name 'appBounds' does not exist in the current context	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	73	Active
 - Error	CS0103	The name 'appBounds' does not exist in the current context	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	73	Active
 - Error	CS0103	The name 'procid' does not exist in the current context	FullscreenLock	C:\Users\linn\Source\fsl2\FullscreenLock\FullscreenLock\Checker.cs	70	Active

Nah

**Comment by blaberry** [comment]
Should probably add a gitignore and remove all the binary crap tho, tbf

I'll do that when I have some time.

**Comment by RyadaProductions** [comment]
Those errors are probably the case because of an outdated language version on your end.
Are you using visual studio 2017? If so is it updated to the latest version?
If this is the case i can fix it by changing the inline out variable assignments to just be created before the out.
Otherwise it should be solvable by using the latest language version on your end.

**Comment by blaberry** [comment]
It's VS2015

**Comment by RyadaProductions** [comment]
I will update my fork to circumvent the compiler errors.
Although it is advised to upgrade to VS2017.

**Comment by RyadaProductions** [comment]
I removed the inline variable declarations.
You should have no compiler errors anymore on VS2015.

**Comment by blaberry** [comment]
BW doesn't automatically start. (This should already be resolved before I have to test it.)

**Comment by RyadaProductions** [comment]
Should start automatically now.

**Comment by blaberry** [comment]
So it's guaranteed to work?

**Comment by RyadaProductions** [comment]
It is guaranteed to work on my machine. I would assume you want to test it yourself.
The non automatic start was an oversight from me.

**Comment by blaberry** [comment]
CPU usage is now 30-40% for one core, compared to 1-5% for timer-version. Closing this PR until performance issues are resolved.

**Comment by RyadaProductions** [comment]
Performance issues should be fixed now.

Reason it was performance hungry, was because in the old version this was in the code.
```
// Sets the timer interval to 5 seconds.
t.Interval = 100;
```
Due to the comment not matching the time you set the interval to I thought it was unnecessary to add any delay to it to improve response time on the user their end.
I added a sleep of 100ms to the end of the BW which solves the high usage and makes it hit 5% cpu usage on a single core at most inside of a windows 10 VM, which is lower than the timer version which ended up hitting 8% on my end.

**Pull request closed without merging**
